
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 600

GRID_WIDTH = 1600
GRID_HEIGHT = 600

CELL_WIDTH = 5
CELL_HEIGHT = 5

GRID_SIZE_X = int(GRID_WIDTH / CELL_WIDTH)
GRID_SIZE_Y = int(GRID_HEIGHT / CELL_HEIGHT)
print(f'Grid size is {(GRID_SIZE_X, GRID_SIZE_Y)}')

COLOR_BACKGROUND = (50, 80, 150)
COLOR_DIRT = (100, 80, 60)

GROUND_DEPTH = 10

GENERATION_TIME = 5.0
GENERATION_SIZE = 100
